name: Build and Submit Dependencies

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Resolve Maven dependencies
        run: mvn dependency:resolve --batch-mode --no-transfer-progress

      - name: Build with Maven
        run: mvn clean install --batch-mode --no-transfer-progress

      - name: Submit dependency graph
        uses: advanced-security/maven-dependency-submission-action@v3
